spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: Welcome1
  datasource:
    #    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employees?serverTimezone=Asia/Shanghai
    username: root
    password: 123456